id: PE8A9CB76
initial_creation_type: input
source_metadata:
  title: Lungta Series
  language: bo
  description: 'Texts on the theme of Lungta (rlung rta/klung rta) or Windhorse, including
    chants to accompany the raising of prayer flags:'
  volume:
    cc3566c287804a3cb4fa3a2fa127cc37:
      title: Windhorse Practice of Tārā
      parent: Prayers
    5c260b62493b4af1a6cb6e42e9d3f0d6:
      title: Raising the Windhorse
      parent: Prayers
    5814e59cfcb5414daa4526fab81a1189:
      title: Prayer to Gyaltsen Tsemö Pung Gyen
      parent: Prayers
    0f9fd8a4ed9d46aba277df862f4ba405:
      title: Brief Gesar Windhorse Invocation
      parent: Prayers
    20b2537f888344269219071bcccaeb61:
      title: Brief Windhorse Invocation
      parent: Prayers
    21dfe1897e42493595f5cede6df5de19:
      title: Daily Lungta Recitation
      parent: Prayers
    75680fec6a2349829653082192497e07:
      title: Short Windhorse Prayer to Gesar
      parent: Prayers
    8004da861fdd463db1f18d91a2865753:
      title: The Swift Fulfilment of All Wishes—Offering the Flag of Windhorse
      parent: Prayers
    b14b6eebccff4f3eaf8e7c409b35637e:
      title: Brief Windhorse Practice of Tārā
      parent: Prayers
created_at: '2022-03-01T04:29:20.282444'
last_modified_at: '2022-03-01T04:29:20.282447'
